version: '3'
services:
  tensorboard:
    image: tensorflow/tensorflow:2.12.0
    volumes:
      - ./logs:/logs
    command: ["tensorboard", "--logdir", "/logs", "--host", "0.0.0.0"]
    networks:
      - tensorboard_network

  nginx:
    image: nginx-basic-auth
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6006:80"
    depends_on:
      - tensorboard
    environment: 
      - USERNAME=admin
      - PASSWORD=admin
    networks:
      - tensorboard_network

networks:
  tensorboard_network: